# Generated by Django 5.2 on 2025-04-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_recurringrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringrule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
