# Generated by Django 5.2 on 2025-04-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_category_is_predefined_alter_expense_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
